members:
  - name: AmazonServices
  - name: Cassandra
  - name: CXF
    update-policy: micro
  - name: Debezium
  - name: GoogleCloudServices
  - name: Hazelcast
  - name: io.quarkiverse.config
  - name: io.quarkiverse.qute.web
  - name: io.quarkiverse.vault
  - name: LangChain4j
  - name: MCPServer
  - name: OperatorSDK
  - name: QpidJMS
  - name: Quarkus Flow

branches:
  latest:
    default-update-policy: micro
    members:
      - name: AmazonServices
      - name: Cassandra
      - name: CXF
      - name: Debezium
      - name: GoogleCloudServices
      - name: Hazelcast
      - name: io.quarkiverse.config
      - name: io.quarkiverse.qute.web
      - name: io.quarkiverse.vault
      - name: LangChain4j
      - name: MCPServer
      - name: OperatorSDK
      - name: QpidJMS
      - name: Quarkus Flow
  3.33:
    default-update-policy: micro
    members:
      - name: AmazonServices
      - name: Cassandra
      - name: CXF
      - name: Debezium
      - name: GoogleCloudServices
      - name: Hazelcast
      - name: io.quarkiverse.config
      - name: io.quarkiverse.qute.web
      - name: io.quarkiverse.vault
      - name: LangChain4j
      - name: MCPServer
      - name: OperatorSDK
      - name: QpidJMS
  3.27:
    default-update-policy: micro
    members:
      - name: AmazonServices
      - name: Cassandra
      - name: CXF
      - name: Debezium
      - name: GoogleCloudServices
      - name: Hazelcast
      - name: io.quarkiverse.config
      - name: io.quarkiverse.qute.web
      - name: io.quarkiverse.vault
      - name: LangChain4j
      - name: MCPServer
      - name: OperatorSDK
      - name: QpidJMS
  3.20:
    default-update-policy: micro
    members:
      - name: AmazonServices
      - name: Cassandra
      - name: CXF
      - name: Debezium
      - name: GoogleCloudServices
      - name: Hazelcast
      - name: io.quarkiverse.config
      - name: io.quarkiverse.qute.web
      - name: io.quarkiverse.vault
      - name: LangChain4j
      - name: MCPServer
      - name: OperatorSDK
      - name: QpidJMS
